### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stefnotch** [dfkeenan/XenkoToolkit#3]
You might want to change this line: https://github.com/dfkeenan/XenkoToolkit/blob/ba6e735f17f3c4be979ab5732daa6efbd6faf087/LICENSE.txt#L189

Or, alternatively, you can change your GitHub username. 😛

**Comment by dfkeenan** [comment]
Whoops, hahahaha. I think All my projects would be like that.

**Comment by dfkeenan** [comment]
On closer inspection that is just giving you a suggestion of what format of copy right notices to put at the top of source files, if you wish to do so.

I will close this issue for now.

Thanks, once again.
