### ISSUE TITLE
Mapping from "Clamp01()" to "Clamp()" wrong

### ISSUE THREAD

**Issue by Saber-1980** [dfkeenan/XenkoToolkit#6]
**Release Type**:
NuGet

**Version**
v0.9.0-alpha

**Platform(s)**
Windows

**Describe the bug**
I think I found an error in the method `MathUtilEx.Clamp01()`. Internally, the Stride method `MathUtil.Clamp()` is invoked, but it seems that the order of the parameters is wrong.

According to the Stride documentation the parameter sequence is **[value]**, [min], [max]. However, the call is performed with [min], [max], **[value]**.

If I understand this correctly, then this line would have to be changed from ...
`public static float Clamp01(float value) => MathUtil.Clamp(0, 1, **value**);`
... to ...
`public static float Clamp01(float value) => MathUtil.Clamp(**value**, 0, 1);`

Could you check that, please?

**To Reproduce**
The following source code should actually produce identical values, but it does not:
```
                // Returns 0.0f.
                float a = MathUtil.Clamp(-0.04f, 0.0f, 1.0f);

                // Returns 1.0f - but should be also 0.0f?
                float b = MathUtilEx.Clamp01(-0.04f);
```

**Expected behavior**`
MathUtilEx.Clamp01()` should provide identical results to `MathUtil.Clamp()`.

Best regards

**Comment by dfkeenan** [comment]
Thanks for the bug report @Saber-1980. I have fixed it. I'll do a release soonish.

**Comment by Saber-1980** [comment]
Great, thanks a lot @dfkeenan ! :-)

**Comment by dfkeenan** [comment]
I have published a new version of the NuGet package. I will close this issue for now.
