### ISSUE TITLE
Stride 4.2

### ISSUE THREAD

**Issue by LanceJZ** [dfkeenan/XenkoToolkit#7]
# Question and/or Comment
I hope this is updated for 4.2 soon. Thank you.

**Comment by dfkeenan** [comment]
Hi,

I haven't been using Stride for quite some time and so have not kept this repo up-to-date.

Is there code in this toolkit that the [Community Toolkit](https://github.com/stride3d/stride-community-toolkit) doesn't have?

There is an open issue  for including more of this toolkit into community toolkit. Perhaps it would be a good idea to talk to the team that maintains that repo about what you want.  https://github.com/stride3d/stride-community-toolkit/issues/16

Thanks,
dfkeenan

**Comment by dfkeenan** [comment]
Hi,

I am in the process of shutting down this project. The APIs from this project have now been added to the [Community Toolkit](https://github.com/stride3d/stride-community-toolkit). 

You should hopefully just be able to start using the latest [Stride.CommunityToolkit](https://www.nuget.org/packages/Stride.CommunityToolkit/) and update using statements.

Thanks,
dfkeenan
